#!/bin/bash

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PYENV_ROOT/shims:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"
source $HOME/.poetry/env

pyenv global 3.9.0
poetry env use 3.9.0
