# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airmobisim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='airmobisim.proto',
  package='airmobisim',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61irmobisim.proto\x12\nairmobisim\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbf\x01\n\nAirMobiSim\x12\x35\n\x05Start\x12\x16.google.protobuf.Empty\x1a\x14.airmobisim.Response\x12\x42\n\x12\x45xecuteOneTimeStep\x12\x16.google.protobuf.Empty\x1a\x14.airmobisim.Response\x12\x36\n\x06\x46inish\x12\x16.google.protobuf.Empty\x1a\x14.airmobisim.Responseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='airmobisim.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='airmobisim.Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'airmobisim_pb2'
  # @@protoc_insertion_point(class_scope:airmobisim.Response)
  ))
_sym_db.RegisterMessage(Response)



_AIRMOBISIM = _descriptor.ServiceDescriptor(
  name='AirMobiSim',
  full_name='airmobisim.AirMobiSim',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=91,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='airmobisim.AirMobiSim.Start',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ExecuteOneTimeStep',
    full_name='airmobisim.AirMobiSim.ExecuteOneTimeStep',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Finish',
    full_name='airmobisim.AirMobiSim.Finish',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIRMOBISIM)

DESCRIPTOR.services_by_name['AirMobiSim'] = _AIRMOBISIM

# @@protoc_insertion_point(module_scope)
