// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: airmobisim.proto

#include "airmobisim.pb.h"
#include "airmobisim.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace airmobisim {

static const char* AirMobiSim_method_names[] = {
  "/airmobisim.AirMobiSim/Start",
  "/airmobisim.AirMobiSim/ExecuteOneTimeStep",
  "/airmobisim.AirMobiSim/Finish",
};

std::unique_ptr< AirMobiSim::Stub> AirMobiSim::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AirMobiSim::Stub> stub(new AirMobiSim::Stub(channel));
  return stub;
}

AirMobiSim::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Start_(AirMobiSim_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExecuteOneTimeStep_(AirMobiSim_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Finish_(AirMobiSim_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AirMobiSim::Stub::Start(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::airmobisim::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Start_, context, request, response);
}

void AirMobiSim::Stub::experimental_async::Start(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::airmobisim::Response* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Start_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::airmobisim::Response>* AirMobiSim::Stub::AsyncStartRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::airmobisim::Response>::Create(channel_.get(), cq, rpcmethod_Start_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::airmobisim::Response>* AirMobiSim::Stub::PrepareAsyncStartRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::airmobisim::Response>::Create(channel_.get(), cq, rpcmethod_Start_, context, request, false);
}

::grpc::Status AirMobiSim::Stub::ExecuteOneTimeStep(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::airmobisim::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ExecuteOneTimeStep_, context, request, response);
}

void AirMobiSim::Stub::experimental_async::ExecuteOneTimeStep(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::airmobisim::Response* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ExecuteOneTimeStep_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::airmobisim::Response>* AirMobiSim::Stub::AsyncExecuteOneTimeStepRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::airmobisim::Response>::Create(channel_.get(), cq, rpcmethod_ExecuteOneTimeStep_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::airmobisim::Response>* AirMobiSim::Stub::PrepareAsyncExecuteOneTimeStepRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::airmobisim::Response>::Create(channel_.get(), cq, rpcmethod_ExecuteOneTimeStep_, context, request, false);
}

::grpc::Status AirMobiSim::Stub::Finish(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::airmobisim::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Finish_, context, request, response);
}

void AirMobiSim::Stub::experimental_async::Finish(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::airmobisim::Response* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Finish_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::airmobisim::Response>* AirMobiSim::Stub::AsyncFinishRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::airmobisim::Response>::Create(channel_.get(), cq, rpcmethod_Finish_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::airmobisim::Response>* AirMobiSim::Stub::PrepareAsyncFinishRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::airmobisim::Response>::Create(channel_.get(), cq, rpcmethod_Finish_, context, request, false);
}

AirMobiSim::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AirMobiSim_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AirMobiSim::Service, ::google::protobuf::Empty, ::airmobisim::Response>(
          std::mem_fn(&AirMobiSim::Service::Start), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AirMobiSim_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AirMobiSim::Service, ::google::protobuf::Empty, ::airmobisim::Response>(
          std::mem_fn(&AirMobiSim::Service::ExecuteOneTimeStep), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AirMobiSim_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AirMobiSim::Service, ::google::protobuf::Empty, ::airmobisim::Response>(
          std::mem_fn(&AirMobiSim::Service::Finish), this)));
}

AirMobiSim::Service::~Service() {
}

::grpc::Status AirMobiSim::Service::Start(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::airmobisim::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AirMobiSim::Service::ExecuteOneTimeStep(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::airmobisim::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AirMobiSim::Service::Finish(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::airmobisim::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace airmobisim

